
services:
  webhook:
    container_name: webhook
    hostname: webhook
    image: ghcr.io/axjab/webhook:latest
    restart: always
    ports:
    - "127.0.0.1:8080:8080"
    environment:
    - WHD_HOOK_SCRIPTS=/scripts
    volumes:
    - /srv/hook:/scripts
